from . import database
import requests
from colorama import init, Fore
from os import system as terminator
from modules import getparse
from modules import proxyguy
init()


def __print_founds(obj):
    terminator('rm -f adminlist.afcat.txt && clear')
    print('\nI FOUND THESE:\n')
    for i in obj:
        print(Fore.YELLOW+'---> '+Fore.GREEN+i+Fore.RESET+'\n')
    with open('adminlist.afcat.txt', 'a') as f:
        f.write('GENERATED BY AFCAT:)\n')
        f.write('\n'.join(obj))
    print(Fore.BLUE, '\nlist saved as: adminlist.afcat.txt', Fore.RESET)


def find_admin():
    FOUNDs = []
    j = 0
    prc = False
    try:
        url = getparse.get()
        prc = True
        for i in database.admin_list:
            code = requests.get(url + i,proxies={'http':proxyguy.getproxy(), 'https' : proxyguy.getproxy()}).status_code
            if code == 200:
                print(Fore.LIGHTGREEN_EX,
                      'FOUND! ----[   ', url + i, '   ]\n', Fore.RESET)
                FOUNDs.append(url+i)
                j += 1
            else:
                print(Fore.RED, 'NOT FOUND ----[ ', url+i, ' ]\n', Fore.RESET)
        else:
            if j == 0:
                print(Fore.LIGHTRED_EX, 'NOTHING FOUND:(', Fore.RESET)
            else:
                print(Fore.LIGHTBLUE_EX, '\nFinished Processing.', Fore.RESET)
                __print_founds(FOUNDs)
    except ConnectionError:
        print ("Could not connect:(\ncheck your internet connection.")
        input ('Press Enter to Continue')
    except KeyboardInterrupt:
        if prc:
            print(Fore.YELLOW, 'Stopped Processing.\n', Fore.RESET)
            if j == 0:
                print(Fore.LIGHTRED_EX, 'NOTHING FOUND:(', Fore.RESET)
            else:
                print(Fore.LIGHTBLUE_EX, '\nFinished Processing.', Fore.RESET)
                __print_founds(FOUNDs)
            
        else:
            print('\nExiting Find Admin Mode...')
    except:
        print(Fore.RED, 'Invalid URL GIVEN:(', Fore.RESET)
        ask = input('\nTry Again? [y/n]: ').lower()
        if ask == 'y':
            terminator('clear')
            find_admin()
        elif ask == 'n':
            exit('\nGOODBYE DEAR!')
        else:
            exit('\nwrong choice again! I\'m leaving...')
